name: Deploy to GitHub Pagesname: Deploy to GitHub Pagesname: Deploy to GitHub Pages



on:

  push:

    branches:on:on:

      - main

      - master  push:  push:



permissions:    branches:    branches:

  contents: write

  pages: write      - main      - main



jobs:      - master      - master

  build-and-deploy:

    runs-on: ubuntu-latest



    steps:permissions:permissions:

      - name: Checkout

        uses: actions/checkout@v3  contents: write  contents: write



      - name: Setup Flutter  pages: write  pages: write

        uses: subosito/flutter-action@v2

        with:

          flutter-version: '3.13.9'

          channel: 'stable'jobs:jobs:

          cache: true

          cache-key: flutter-3.13.9  build-and-deploy:  build-and-deploy:

          

      - name: Install dependencies    runs-on: ubuntu-latest    runs-on: ubuntu-latest

        run: flutter pub get



      - name: Build web app

        run: |    steps:    steps:

          flutter build web \

            --release \      - name: Checkout      - name: Checkout

            --base-href '/' \

            --dart-define=API_BASE_URL=https://alumno-backend-node.onrender.com        uses: actions/checkout@v3        uses: actions/checkout@v3



      - name: Deploy to GitHub Pages

        uses: peaceiris/actions-gh-pages@v3

        with:      - name: Setup Flutter      - name: Setup Flutter

          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: ./build/web        uses: subosito/flutter-action@v2        uses: subosito/flutter-action@v2

          force_orphan: true

          cname: app.carnetdigital.space        with:        with:

          flutter-version: '3.13.9'          flutter-version: '3.13.9'

          channel: 'stable'          channel: 'stable'

          cache: true          cache: true

          cache-key: flutter-3.13.9          cache-key: flutter-3.13.9

                    

      - name: Install dependencies      - name: Install dependencies

        run: flutter pub get        run: flutter pub get



      - name: Build web app      - name: Build web app

        run: |        run: |

          flutter build web \          flutter build web \

            --release \            --release \

            --base-href '/' \            --base-href '/' \

            --dart-define=API_BASE_URL=https://alumno-backend-node.onrender.com            --dart-define=API_BASE_URL=https://alumno-backend-node.onrender.com



      - name: Deploy to GitHub Pages      - name: Deploy to GitHub Pages

        uses: peaceiris/actions-gh-pages@v3        uses: peaceiris/actions-gh-pages@v3

        with:        with:

          github_token: ${{ secrets.GITHUB_TOKEN }}          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: ./build/web          publish_dir: ./build/web

          force_orphan: true          force_orphan: true

          cname: app.carnetdigital.space          cname: app.carnetdigital.space