name: Deploy to GitHub Pages
on:
  push:
    branches: [main, master]
permissions:
  contents: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build web --release --base-href '/' --web-renderer html --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false --dart-define=FLUTTER_WEB_USE_SKIA=false --dart-define=FLUTTER_WEB_CANVASKIT_URL=none --dart-define=FLUTTER_WEB_AUTO_DETECT=false --dart-define=API_BASE_URL=https://alumno-backend-node.onrender.com
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        force_orphan: true
        cname: app.carnetdigital.space
